### ISSUE TITLE
libjsonhelper load error

### ISSUE THREAD

**Issue by rbrigden** [FraMecca/torchat#1]
./build/main: error while loading shared libraries: libjsonhelper.so: cannot open shared object file: No such file or directory

^^ been wrestling with this for a bit. I'm on macOS, so I have torchat building in an ubuntu based container.

**Comment by GallaFrancesco** [comment]
If you need a quick fix just: 

export $LD_LIBRARY_PATH=$(pwd)/build
./build/main 8000

**Comment by FraMecca** [comment]
The makefile has been changed to resolve the issue. Now the linker sets the shared libraries directory to build/ .
Try to compile again:
`make debug`
and then run torchat
`./build/main 8000`
